name: CSharp CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Run unit checks
        run: dotnet test Timesheet.Test/Timesheet.Test.csproj --filter FullyQualifiedName~Timesheet.Test.Unit 
